name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push api/ to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git subtree push --prefix=api https://hamynguyen:$HF_TOKEN@huggingface.co/spaces/hamynguyen/hdb-price-estimator main
